### ISSUE TITLE
Text area limit

### ISSUE THREAD

**Issue by danielrodd** [humhub-contrib/legal#1]
Legal text is normally pretty large given policies and terms, but text area limits text to a certain point. how to increate word limit? I was only able to edit legal/views/admin/page.php file on line 105: 

 `          <?= $form->field($pages[$languageKey], '[' . $languageKey . ']content')->widget(MarkdownField::class, ['filesInputName' => 'PageFiles[' . $languageKey . ']', 'rows' => 20]); ?>`

Increased rows to 20 but it was no use. I'm still textarea limited.

**Comment by danielrodd** [comment]
Search and schemed high and low on the entire humhub library and files, line by line on every file related to markdown, couldn't find a solution. After days of trying, will switch to custom pages. Funny and ironic that a legal module would limit text. Should be in html instead of markdown.

**Comment by luke-** [comment]
There are two options at the markdown editor to adjust the text area size (Top Right = Fullscreen Edit, Bottom Right = Resize).

**Comment by luke-** [comment]
https://github.com/humhub-contrib/legal/issues/2 - Maybe this would also solves the issue
