### ISSUE TITLE
Make Age restriction configurable

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/legal#10]
From the [community site](https://community.humhub.com/s/general-discussion/?contentId=224740)

**Comment by ArchBlood** [comment]
I would like to try and take on this task if it's not of any importance at this time

**Comment by luke-** [comment]
Great!

**Comment by ArchBlood** [comment]
I've not forgotten about this just doing the finishing touches then I'll create a p/r to be reviewed :+1:

**Comment by ArchBlood** [comment]
@luke- can I get a confirmation? :smile:

**Comment by luke-** [comment]
Sorry, this has been lost. I have just reviewed the PR.

**Comment by ArchBlood** [comment]
Alright completed the changes requested :smile:

**Comment by ArchBlood** [comment]
Should be able to close this now 😃
