### ISSUE TITLE
Add acceptance tests

### ISSUE THREAD

**Issue by luke-** [humhub-contrib/legal#18]

**Comment by yurabakhtin** [comment]
@luke- I started this in PR https://github.com/humhub-contrib/legal/pull/52 , currently it is done only for 2 options "Terms and Conditions" and "Privacy Policy", for others I will do later.
But please note the tests are broken for v1.7, does it mean I should find what min version works without errors and then increase it in the file `module.json`?

**Comment by yurabakhtin** [comment]
@luke- I added tests for all other options in the commit https://github.com/humhub-contrib/legal/pull/52/commits/4ee4783a39f6eab00f6f760ad03876697196eec2.

Also please review next commits where I tried to find minimum HumHub version where all tests works without errors, but it is strange why they are broken even on v1.10.
