### ISSUE TITLE
New feature: Terms and Conditions by group

### ISSUE THREAD

**Issue by funkycram** [humhub-contrib/legal#19]
I need to develop the possibility to force users that are member of a specific group to agree Terms and Conditions for this group.

The idea is to have in the groups settings an additional tab, " Terms and Conditions":
![image](https://user-images.githubusercontent.com/23310825/108586061-62f71200-734c-11eb-8c83-3d07b8ac5797.png)

As soon as a user is member of this group, he needs to agree to the Terms and Conditions of this group (if enabled for this group).
As long as he is not a member of this group, the Terms and Conditions of this group will not be shown to him.

Would you like me to develop this feature in this Legal module and propose a new release of it or do you prefer me to develop an external module for it ?

**Comment by luke-** [comment]
We were just discussing that and  prefer the solution as a separate module, since we can't find many use cases for the feature and it would add a lot of complexity. 

How do you see it? Are we overlooking use cases here? 
Otherwise, we are actually open to both solutions.

**Comment by funkycram** [comment]
Thanks for having taken in consideration this proposal.
I have 2 Humhub for organizations having sub communities.
That's why we need to have specific terms for them.
I cannot tell if many Humhub platforms needs that.
So I will create a separate module.
