### ISSUE TITLE
Infinite Looping

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/legal#35]
Currently, it seems that the Legal Tools module is suffering from infinite loops in some areas

Similar to https://github.com/humhub/twofa/issues/29

**Comment by luke-** [comment]
Can you please provide steps to reproduce?

**Comment by ArchBlood** [comment]
It's a rather strange one, as I've only been able to reproduce it once when creating new accounts

https://community.humhub.com/content/perma?id=242808
