### ISSUE TITLE
Agreement Feature Should Be Optional

### ISSUE THREAD

**Issue by miqrogroove** [humhub-contrib/legal#36]
I tried setting up a Privacy Policy.  I liked the overall look and feel of the module.

The next time I logged in, I could not proceed to the Dashboard without agreeing to the new Privacy Policy.  To make matters worse, I couldn't even access the admin pages.

For my purposes, I'd rather not force any of my users to agree or even read the Privacy Policy.  I'd only want it to be available as a link.

**Comment by luke-** [comment]
@miqrogroove In the meantime you can also create pages in the footer menu, maybe it will solve your problem if you just create a page there.
