### ISSUE TITLE
(Wondering) Is it displayed in non-default language?

### ISSUE THREAD

**Issue by tosintech-web** [humhub-contrib/legal#39]
I use the humhub(ver.1.9.1: in the setting of default language with Japanese) legal module(ver.1.2.2). And we wrote the legal module's "Terms & Conditions" using "Japanese" and "English". (Thank you for multi language function.) We set "Japanese" to the default language in the legal module settings.

By the way, an English User registering to the system and he click "Terms & Conditions" in the page. Opening the link, it displays "Japanese" terms and conditions.  If my memory serves me correctly, it worked correct at humhub Ver.1.8.2, legal module ver.1.2.1.

I wondering if it were something bug about language settings.

If other similar cases are reported, how about to investigate?

Thank you.

**Comment by ArchBlood** [comment]
Should be the user preference that is used, otherwise, if it's a guest then it should be default based on the admin section selected language. 🤔

**Comment by luke-** [comment]
Perhaps there is a problem here with British English vs. American English?
