### ISSUE TITLE
Registration form checkbox links not working

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/legal#4]
"Back" button not directing to where it should

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- I have fixed only the back button in PR https://github.com/humhub-contrib/legal/pull/51

![legal-links](https://user-images.githubusercontent.com/6995524/177915513-a3fc6055-4b64-4af6-8159-de119f5b0abd.png)

But I cannot understand this "Registration form checkbox links not working", could you tell me step by step or with screenshot what exactly doesn't work? Thanks.

**Comment by luke-** [comment]
Maybe it's already fixed since this issue is very old. But thanks for the check & PR!
