### ISSUE TITLE
Legal Update broken

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/legal#42]
Resetting the approvals to the terms does not seem to trigger a 'legal update'´/reset of the approvals.

HH 1.10 beta 1

**Comment by luke-** [comment]
Seems like it's related to caching. Since the update appeard some days after.

**Comment by yurabakhtin** [comment]
yes, we should run invalidate caching because the settings are deleted "manually" here https://github.com/humhub-contrib/legal/blob/master/controllers/AdminController.php#L94.

**Comment by luke-** [comment]
@yurabakhtin Ah thats it. Can you fix this?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub-contrib/legal/pull/43.

**Comment by luke-** [comment]
@yurabakhtin Thansk!
