### ISSUE TITLE
Links incorrect

### ISSUE THREAD

**Issue by DerKleene** [humhub-contrib/legal#54]
Hello,
when I activate this addon and want to click a link,
then it takes the IP address and not the URL that is stored.
How can this be changed?
This happens with all links from this addon.
So you can not call up the terms and conditions, imprint, etc. from outside.
Attached is a picture
![links_icorrect](https://user-images.githubusercontent.com/19396070/181764918-d8808954-ee00-467e-b8a9-9e6bad13e7eb.png)

**Comment by luke-** [comment]
What is your configured base url at Administration -> Settings -> Base URL?

**Comment by luke-** [comment]
Maybe also interesting: https://docs.humhub.org/docs/admin/reverse-proxy

**Comment by DerKleene** [comment]
Hello,
these are my settings:
![links_incorrect2](https://user-images.githubusercontent.com/19396070/181779722-b3f4b787-2947-43d2-ba42-bb6fcb65e6bf.png)

Unfortunately I can't try this with the RemoteProxy until Monday, unfortunately I don't have access to the PHP file before that.

**Comment by DerKleene** [comment]
> Maybe also interesting: https://docs.humhub.org/docs/admin/reverse-proxy

Hello,
Thanks for the hint.
after I entered the proxy, everything seems to work now.
If it hadn't occurred to me that it could be the cause.
