### ISSUE TITLE
Compatibility with Humhub 1.14

### ISSUE THREAD

**Issue by funkycram** [humhub-contrib/legal#59]
Since Humhub 1.14, I have: Calling unknown method: humhub\modules\user\components\User::canDeleteAccount()

This is due to:
https://github.com/humhub-contrib/legal/blob/master/views/page/confirm.php#L44
and
https://github.com/humhub-contrib/legal/blob/master/views/page/update.php#L47

`Yii::$app->user->canDeleteAccount()` should be replaced with `Yii::$app->user->getAuthClientUserService()->canDeleteAccount()`.

But I haven't find any mention of this on https://docs.humhub.org/docs/develop/modules-migrate#version-114

**Comment by luke-** [comment]
@funkycram Oh, I overlooked that use. I have now updated the docs, temporarily re-inserted the method in the core and prepared a PR for the Legal module.

**Comment by luke-** [comment]
https://github.com/humhub-contrib/legal/pull/60

**Comment by funkycram** [comment]
Thanks!
