### ISSUE TITLE
1.5.0-beta1 compatibility

### ISSUE THREAD

**Issue by garthh** [humhub-contrib/legal#6]
Hi, I've update Humhub with 1.5.0-beta1 and legal module don't work anymore.

The file or directory to be published does not exist: /home/www-data/forges.portes-imaginaire.org/ROOT/protected/humhub/modules/ui/form/resources

**Comment by buddh4** [comment]
Someone reported the same issue in breaking news module, seems to be related with the Markdown assets. I could not recreate the issue on a fresh installation, could you check if the directory exists, also does this happen in [production](https://docs.humhub.org/docs/admin/security#enable-production-mode) as well as debug mode?

**Comment by garthh** [comment]
Hi,
I've create the "resources" directory and it's run again.
Thank you

**Comment by garthh** [comment]
the markdown field doesn't appear on legal forms

**Comment by luke-** [comment]
See here: https://github.com/humhub-contrib/breakingnews/issues/13
