### ISSUE TITLE
Show legal pages to check just after saving the configuration

### ISSUE THREAD

**Issue by funkycram** [humhub-contrib/legal#62]
If, in the configuration, you check e.g. "Terms and Conditions", you think you will have to check the terms page.
But because the session for `Events::SESSION_KEY_LEGAL_CHECK` is already checked, it doesn't happen, and you think it doesn't work.
Proposal: remove the session after configuration saving.

**Comment by funkycram** [comment]
@luke- PR https://github.com/humhub-contrib/legal/pull/63

**Comment by luke-** [comment]
@funkycram Thanks!
