### ISSUE TITLE
Allow custom HTML links (e.g. Google Adwords OptOut)

### ISSUE THREAD

**Issue by luke-** [humhub-contrib/legal#7]
Links like not parsed as HTML:

```
<a id="ga-opt-out" href="#!">Click here to disable tracking.</a>
```
Solution: Allow basic HTML in the Markdown Editor

@buddh4 Related to #2 - Do you see any chance to use the new markdown editor here? Or should we use the old markdown editor here?

**Comment by buddh4** [comment]
Which editor is currently in use? Generally we can try to allow html output in specific cases like this but this is currently not supported. Also allowing id attributes is not safe and should not be allowed for non admin generated content.

**Comment by buddh4** [comment]
Maybe we can integrate such opt out options outside of the richtext?

**Comment by luke-** [comment]
Currently the old Markdown Editor is used. It should probably support this well in combination with the HTML Purifier.

Extra links are not an option as there could be many different tracking opt out links.

**Comment by buddh4** [comment]
If we had a dedicated place for such buttons in the layout and an extra input field? 
We could also just switch between a HTML editor view und richtext view, but this would require saving the format also.

**Comment by luke-** [comment]
As a workaround we will create a custom page (HTML) with the Google OptOut link and link from the Legal module (RichtText) to this page.

At a later stage we can implement buttons or HTML formats directly in the Legal module.
