### ISSUE TITLE
Legal texts are only accessible when user's are logged in

### ISSUE THREAD

**Issue by hbel** [humhub-contrib/legal#8]
In HumHub 1.6, the legal text links are still visible on the login page, but clicking them just reloads the page. It seems like the legal texts are no longer accessible for users that are not logged in. If I login and access the system as a registered user, I can click on the links on the bottom of the page and they behave as expected.

**Comment by luke-** [comment]
Fixed: https://github.com/humhub-contrib/legal/commit/632fb05af10c6d148decd68756684309d9c98636
